'use strict';

const FailureCodes = Object.freeze({
  ACCEPT: 'ACCEPT',
  BAD_CANONICALIZATION: 'BAD_CANONICALIZATION',
  BAD_SIGNATURE: 'BAD_SIGNATURE',
  UNKNOWN_RULESET: 'UNKNOWN_RULESET',
  UNKNOWN_CANONICALIZATION: 'UNKNOWN_CANONICALIZATION',
  STATE_ROOT_MISMATCH: 'STATE_ROOT_MISMATCH',
  INVALID_WITNESS: 'INVALID_WITNESS',
  DEVICE_NOT_BOUND: 'DEVICE_NOT_BOUND',
  DEVICE_REVOKED: 'DEVICE_REVOKED',
  CAPABILITY_NOT_FOUND: 'CAPABILITY_NOT_FOUND',
  POLICY_DENIED: 'POLICY_DENIED',
  REQUEST_MISMATCH: 'REQUEST_MISMATCH',
  NONCE_REPLAY: 'NONCE_REPLAY',
  PROOF_EXPIRED: 'PROOF_EXPIRED',
  STATE_STALE: 'STATE_STALE',
  EPOCH_FORKED: 'EPOCH_FORKED',
});

module.exports = {
  FailureCodes,
};
